"""empty message

Revision ID: 04f079d131ee
Revises: b16639ed2f2d
Create Date: 2024-05-08 11:03:44.066114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f079d131ee'
down_revision = 'b16639ed2f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('digimon1_id', sa.Integer(), nullable=True),
    sa.Column('digimon2_id', sa.Integer(), nullable=True),
    sa.Column('digimon3_id', sa.Integer(), nullable=True),
    sa.Column('team_status', sa.String(length=50), nullable=True),
    sa.Column('digimon1_life', sa.Integer(), nullable=True),
    sa.Column('digimon1_stamina', sa.Integer(), nullable=True),
    sa.Column('digimon1_level', sa.Integer(), nullable=True),
    sa.Column('digimon1_attack', sa.Integer(), nullable=True),
    sa.Column('digimon1_defense', sa.Integer(), nullable=True),
    sa.Column('digimon1_type', sa.String(length=50), nullable=True),
    sa.Column('digimon2_life', sa.Integer(), nullable=True),
    sa.Column('digimon2_stamina', sa.Integer(), nullable=True),
    sa.Column('digimon2_level', sa.Integer(), nullable=True),
    sa.Column('digimon2_attack', sa.Integer(), nullable=True),
    sa.Column('digimon2_defense', sa.Integer(), nullable=True),
    sa.Column('digimon2_type', sa.String(length=50), nullable=True),
    sa.Column('digimon3_life', sa.Integer(), nullable=True),
    sa.Column('digimon3_stamina', sa.Integer(), nullable=True),
    sa.Column('digimon3_level', sa.Integer(), nullable=True),
    sa.Column('digimon3_attack', sa.Integer(), nullable=True),
    sa.Column('digimon3_defense', sa.Integer(), nullable=True),
    sa.Column('digimon3_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['digimon1_id'], ['digimon.id'], ),
    sa.ForeignKeyConstraint(['digimon2_id'], ['digimon.id'], ),
    sa.ForeignKeyConstraint(['digimon3_id'], ['digimon.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_team')
    # ### end Alembic commands ###
