"""empty message

Revision ID: 89b70aa7faf7
Revises: 4bef2030c07c
Create Date: 2024-04-29 15:53:03.758085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b70aa7faf7'
down_revision = '4bef2030c07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digimon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('life', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('defense', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lore', sa.String(length=1000), nullable=True))
        batch_op.drop_column('vida')
        batch_op.drop_column('nome')
        batch_op.drop_column('defesa')
        batch_op.drop_column('tipo')
        batch_op.drop_column('ataque')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digimon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ataque', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('defesa', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('vida', sa.INTEGER(), nullable=True))
        batch_op.drop_column('lore')
        batch_op.drop_column('type')
        batch_op.drop_column('defense')
        batch_op.drop_column('atk')
        batch_op.drop_column('life')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
