"""empty message

Revision ID: 9507e5edf415
Revises: b10b968b388b
Create Date: 2024-04-29 16:51:17.668684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9507e5edf415'
down_revision = 'b10b968b388b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digimon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprite', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('sprit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digimon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprit', sa.BLOB(), nullable=True))
        batch_op.drop_column('sprite')

    # ### end Alembic commands ###
