"""empty message

Revision ID: 995bf04e3e29
Revises: 04f079d131ee
Create Date: 2024-05-08 11:09:36.386922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995bf04e3e29'
down_revision = '04f079d131ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage')
    # ### end Alembic commands ###
