"""empty message

Revision ID: a58bfeeddd26
Revises: 995bf04e3e29
Create Date: 2024-05-08 11:12:01.739514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58bfeeddd26'
down_revision = '995bf04e3e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('digimon1_id', sa.Integer(), nullable=True),
    sa.Column('digimon2_id', sa.Integer(), nullable=True),
    sa.Column('digimon3_id', sa.Integer(), nullable=True),
    sa.Column('team_status', sa.String(length=50), nullable=True),
    sa.Column('digimon1_life', sa.Integer(), nullable=True),
    sa.Column('digimon1_stamina', sa.Integer(), nullable=True),
    sa.Column('digimon1_level', sa.Integer(), nullable=True),
    sa.Column('digimon1_attack', sa.Integer(), nullable=True),
    sa.Column('digimon1_defense', sa.Integer(), nullable=True),
    sa.Column('digimon1_type', sa.String(length=50), nullable=True),
    sa.Column('digimon2_life', sa.Integer(), nullable=True),
    sa.Column('digimon2_stamina', sa.Integer(), nullable=True),
    sa.Column('digimon2_level', sa.Integer(), nullable=True),
    sa.Column('digimon2_attack', sa.Integer(), nullable=True),
    sa.Column('digimon2_defense', sa.Integer(), nullable=True),
    sa.Column('digimon2_type', sa.String(length=50), nullable=True),
    sa.Column('digimon3_life', sa.Integer(), nullable=True),
    sa.Column('digimon3_stamina', sa.Integer(), nullable=True),
    sa.Column('digimon3_level', sa.Integer(), nullable=True),
    sa.Column('digimon3_attack', sa.Integer(), nullable=True),
    sa.Column('digimon3_defense', sa.Integer(), nullable=True),
    sa.Column('digimon3_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['digimon1_id'], ['digimon.id'], ),
    sa.ForeignKeyConstraint(['digimon2_id'], ['digimon.id'], ),
    sa.ForeignKeyConstraint(['digimon3_id'], ['digimon.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_team')
    # ### end Alembic commands ###
